name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STOREPASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEYPASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEYALIAS }}" >> android/key.properties
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.x'
          channel: 'stable'
          dart-version: '2.19.6'
      - run: flutter pub get
      - name: Build and Deploy
        run: |
          flutter build appbundle
      - name: Upload Android Release
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: build/app/outputs/bundle/release/app-release.aab
