name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.x'
          channel: 'stable'
          dart-version: '2.19.6'
      - run: flutter pub get
      - run: flutter build appbundle --release
      - uses: actions/upload-artifact@v2
        with:
          name: Release AAB
          path: build/app/outputs/bundle/release/app.aab
