name: AppStore Release
on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install and Select Xcode version
              run: |
                chmod +x install_xcode.sh
                ./install_xcode.sh
              shell: bash
            - name: Your Other Deployment Steps
              run: |
                # Add your deployment steps here
              shell: bash
      
      
      
    # - name: Setup flutter
    #   uses: subosito/flutter-action@v1
    #   with:
    #     flutter-version: "3.10.6"
    #     channel: "stable"
    # - name: Install tools
    #   run: |
    #     flutter pub get
    #     cd ./ios && pod install
    # - name: Decode and Setup SSH Keys and known_hosts for fastlane match
    #   run: |
    #     SSH_PATH="$HOME/.ssh"
    #     mkdir -p "$SSH_PATH"
    #     touch "$SSH_PATH/known_hosts"
    #     echo "$PRIVATE_KEY_BASE64" | base64 --decode > "$SSH_PATH/id_rsa"
    #     chmod 700 "$SSH_PATH"
    #     ssh-keyscan github.com >> ~/.ssh/known_hosts
    #     chmod 600 "$SSH_PATH/known_hosts"
    #     chmod 600 "$SSH_PATH/id_rsa"
    #     eval $(ssh-agent)
    #     ssh-add "$SSH_PATH/id_rsa"
    #   env:
    #     PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY }}
